from .patient import Patient
from .otp_code import OTPCode
from .doctor import Doctor
from .appointment import Appointment
from .health_record import HealthRecord
from .consultation import Consultation
from .medicine import Medicine
from .prescription import Prescription
from .prescription_item import PrescriptionItem
from .inventory_transaction import InventoryTransaction
from .medicine_request import MedicineRequest
from .clinic_setting import ClinicSetting
